"""`fm post grade-handoff`: a hand-off package for grading in DaVinci Resolve (or any external grading tool).

What it is: the effective per-shot grade (from the resolved shots, i.e. shot blocks and canon `look.grade*`), the frame
sequences it applies to, and a README with the manual steps. What it is NOT: DaVinci Resolve is never run, scripted or
checked from here, no .drx/.cube/project file is generated, and nothing claims the Blender compositor grade and a Resolve
grade look the same (different maths: treat the numbers as a starting point for a colourist).

It writes only under 13_delivery/resolve_handoff/ and records nothing in the project state.
"""
from __future__ import annotations

import json
from pathlib import Path

from .errors import FMError
from .io import now_iso, write_json, write_yaml
from .project import Project

HANDOFF_DIR = "13_delivery/resolve_handoff"
FINAL_DIR = "11_render/final"


def _png_depth(path: Path) -> int | None:
    try:
        with open(path, "rb") as fh:
            head = fh.read(26)
        return head[24] if head[:8] == b"\x89PNG\r\n\x1a\n" and head[12:16] == b"IHDR" else None
    except OSError:
        return None


def _frames_info(project: Project, sid: str, frames_dir: Path) -> dict:
    d = frames_dir / sid
    pngs = sorted(d.glob("[0-9][0-9][0-9][0-9].png")) if d.is_dir() else []
    if not pngs:
        return {"dir": project.rel(d), "present": False, "frames": 0}
    return {"dir": project.rel(d), "present": True, "frames": len(pngs), "first": pngs[0].name, "last": pngs[-1].name,
            "png_bit_depth": _png_depth(pngs[0])}


def grade_handoff(project: Project, out: str | Path | None = None, frames_dir: str | Path | None = None) -> dict:
    resolved = project.dir / "09_resolved"
    film_p = resolved / "film.json"
    if not film_p.exists():
        raise FMError("09_resolved/film.json missing: run `fm resolve` first")
    film = json.loads(film_p.read_text(encoding="utf-8"))
    od = Path(out) if out else project.dir / HANDOFF_DIR
    fd = Path(frames_dir) if frames_dir else project.dir / FINAL_DIR
    shots: dict = {}
    graded = 0
    for sid, row in film["shots"].items():
        sp = json.loads((resolved / f"{sid}.json").read_text(encoding="utf-8"))
        g = sp.get("grade")
        graded += bool(g)
        shots[sid] = {"start_frame": row["start"], "frames": row["frames"], "grade": g,
                      "atmosphere": ({k: v for k, v in sp["atmosphere"].items() if k != "rationale"} if sp.get("atmosphere") else None),
                      "rendered": _frames_info(project, sid, fd)}
    fmt = film.get("format") or {}
    edl = sorted((project.dir / "12_post").glob("*.edl"))
    spec = {"schema": "fm.grade_handoff/1", "project": project.slug, "created": now_iso(),
            "fps": fmt.get("fps"), "resolution_px": fmt.get("resolution_px"), "total_frames": film.get("total_frames"),
            "colour_pipeline": {"working": "scene-linear Rec.709 (Blender), baked by the view transform into the PNG frames",
                                "frames_are": "display-referred sRGB (Standard view transform unless a shot grade says otherwise)",
                                "note": "set the Resolve timeline/input colour space to match the frames; fm does not do this"},
            "edl": project.rel(edl[0]) if edl else None, "shots": shots}
    od.mkdir(parents=True, exist_ok=True)
    write_yaml(od / "GRADE_SPEC.yaml", spec)
    write_json(od / "grade_spec.json", spec)
    missing = [s for s, v in shots.items() if not v["rendered"]["present"]]
    shallow = [s for s, v in shots.items() if v["rendered"].get("png_bit_depth") == 8]
    readme = _readme(project, spec, graded, missing, shallow)
    (od / "README_RESOLVE.md").write_text(readme, encoding="utf-8")
    return {"dir": str(od), "files": ["GRADE_SPEC.yaml", "grade_spec.json", "README_RESOLVE.md"], "shots": len(shots),
            "shots_with_grade": graded, "shots_without_frames": missing, "shots_8bit": shallow, "edl": spec["edl"]}


def _readme(project: Project, spec: dict, graded: int, missing: list, shallow: list) -> str:
    lines = [
        f"# DaVinci Resolve grading hand-off: {project.slug}", "",
        "Generated by `fm post grade-handoff`. **DaVinci Resolve is not automated by FILM_MAKER**: nothing here opens, scripts or",
        "checks Resolve. This is a package for a human colourist.", "",
        "## What is in this folder", "",
        "- `GRADE_SPEC.yaml` / `grade_spec.json`: per shot, the frame range, the effective `grade` block (shot block or canon",
        "  `look.grade*`), the atmosphere used, and where the rendered frames are.",
        "- this file.", "",
        "## Steps", "",
        "1. Render the film with the cinematic final profile (`fm blender final --profile cinematic_final`, needs your",
        "   `fm authorize final-render`). Frames land in `11_render/final/<SHOT>/NNNN.png` (16-bit PNG in that profile).",
        "2. In Resolve, create a project at "
        f"{spec['fps']} fps, {spec['resolution_px'][0]}x{spec['resolution_px'][1]}" if spec.get("resolution_px") else
        "2. In Resolve, create a project at the film's fps and resolution",
        "   and import each shot folder as an image sequence.",
        "3. Import the EDL" + (f" (`{spec['edl']}`)" if spec.get("edl") else " (run `fm post edl` to create it)")
        + " to conform the shots in order.",
        "4. Set the clips' input colour space to match the frames (sRGB / Rec.709 gamma 2.2 for the Standard view transform).",
        "5. Grade by hand using `GRADE_SPEC.yaml` as the brief. The numbers are the Blender compositor's lift/gamma/gain,",
        "   saturation and curve: Resolve's maths differs, so they are a starting point, not a match.",
        "6. Export from Resolve (ProRes/H.264 as needed); that file is outside FILM_MAKER's checks (`fm qa delivery` can probe it).", "",
        "## Status of this package", "",
        f"- shots with a grade block: {graded} of {len(spec['shots'])}",
    ]
    if missing:
        lines.append(f"- NO rendered frames yet for: {', '.join(missing)}")
    if shallow:
        lines.append(f"- 8-bit PNG frames (little grading headroom; render with a profile that sets `color_depth: 16`): {', '.join(shallow)}")
    lines += ["", "EXR output is not implemented in `fm blender final` (it writes PNG so `fm post assemble` can read it).", ""]
    return "\n".join(lines)
