"""Human-readable reports generated from state: STATUS.md and CHANGELOG.md."""
from __future__ import annotations

from collections import Counter

from .deps import Graph
from .io import short
from .phases import CONTRACTS, GATE_FOR_PHASE, GATES
from .project import Loaded, Project
from .schemas import ProjectState, Status


def gate_line(gid: str, state: ProjectState, loaded: Loaded, graph: Graph) -> tuple[str, list[str]]:
    from .validate import gate_health  # local import: avoid cycle

    rec = state.gates[gid]
    issues = gate_health(gid, state, loaded, graph)
    status = rec.status + (" (DRIFTED)" if issues else "")
    return status, issues


def next_action(state: ProjectState) -> str:
    gate = GATE_FOR_PHASE.get(state.phase)
    if state.phase == "COMPLETE":
        return "Project complete."
    if state.phase_status == "awaiting_approval" and gate:
        return (f"Human review: `fm approve {gate.id}`, or `fm revise {gate.id} --notes ...` / "
                f"`fm reject {gate.id} --notes ...`")
    if gate and state.gates[gate.id].status == "approved":
        return "Gate approved: `fm advance`"
    req = CONTRACTS.get(state.phase)
    if gate:
        return (f"Produce {state.phase} deliverables"
                + (f" ({', '.join(req.required)})" if req and req.required else "")
                + f", then `fm submit` for {gate.id}")
    return f"Produce {state.phase} deliverables, then `fm advance`"


def render_status(project: Project, state: ProjectState, loaded: Loaded, graph: Graph) -> str:
    stale = graph.stale()
    canon_status = Counter()
    for cid, item in loaded.canon.items():
        lk = state.canon.get(cid)
        canon_status[(lk.status if lk else item.entry.status).value] += 1
    pending_changes = [c for c, s in state.changes.items() if s == Status.PROPOSED]
    L = [
        f"# STATUS — {state.title}",
        "",
        "> Generated by `fm` from the approval ledger. Do not edit by hand.",
        "",
        "```yaml",
        f"project: {state.project}",
        f"sandbox: {str(state.sandbox).lower()}",
        f"current_phase: {state.phase}",
        f"status: {state.phase_status}",
        f"ledger: {state.ledger_seq} records, head {short(state.ledger_head)}",
        "```",
        "",
        f"**Next:** {next_action(state)}",
        "",
        "## Gates",
        "",
        "| Gate | Name | Status | Decided by | Items approved |",
        "|---|---|---|---|---|",
    ]
    all_issues = []
    for gid, g in GATES.items():
        rec = state.gates[gid]
        status, issues = gate_line(gid, state, loaded, graph)
        all_issues += [f"{gid}: {i}" for i in issues]
        L.append(f"| {gid} | {g.name} | {status} | {rec.decided_by or '-'} | "
                 f"{len(rec.approved_hashes) or '-'} |")
    L += ["", "## Canon", ""]
    L.append(", ".join(f"{k}: {v}" for k, v in sorted(canon_status.items())) or "No canon entries yet.")
    L += ["", "## Artifacts", ""]
    if loaded.artifacts:
        L += ["| Artifact | Phase | Status | Hash |", "|---|---|---|---|"]
        for aid, a in sorted(loaded.artifacts.items()):
            st = state.artifacts.get(a.ref, a.meta.status).value
            flag = " (stale)" if a.ref in stale else ""
            L.append(f"| {aid} | {a.meta.phase} | {st}{flag} | {short(a.hash)} |")
    else:
        L.append("None yet.")
    L += ["", "## Shots", ""]
    if loaded.shots:
        L += ["| Shot | Duration | Status | Stage |", "|---|---|---|---|"]
        for sid, s in sorted(loaded.shots.items()):
            flag = " (stale)" if s.ref in stale else ""
            L.append(f"| {sid} | {s.spec.duration_s:g}s | {s.spec.status.value}{flag} | "
                     f"{state.shots.get(sid, 'spec')} |")
    else:
        L.append("None yet.")
    L += ["", "## Attention", ""]
    attention = [*all_issues, *[f"stale: {r}" for r in sorted(stale)],
                 *[f"change awaiting decision: {c}" for c in pending_changes]]
    L += [f"- {a}" for a in attention] or ["Nothing outstanding."]
    if state.authorizations:
        L += ["", "## Authorizations", ""]
        L += [f"- {a.what} ({a.scope}) by {a.by} at {a.at}" for a in state.authorizations]
    return "\n".join(L) + "\n"


def render_changelog(loaded: Loaded) -> str:
    L = ["# CHANGELOG", "",
         "> Generated by `fm` from change requests in `changes/`. Do not edit by hand.", ""]
    if not loaded.changes:
        L.append("No changes to approved decisions yet.")
    for cid in sorted(loaded.changes, reverse=True):
        cr, _ = loaded.changes[cid]
        L += [f"## {cid} — {cr.status.value}", "",
              f"- **Target:** `{cr.target}` (from v{cr.base_version})",
              f"- **Changed:** " + "; ".join(f"`{k}` → {v!r}" for k, v in cr.set.items()),
              f"- **Reason:** {cr.reason}",
              f"- **Proposed:** {cr.proposed_by} at {cr.proposed_at}"]
        if cr.decided_by:
            L.append(f"- **Decided:** {cr.decided_by} at {cr.decided_at}"
                     + (f" — {cr.decision_notes}" if cr.decision_notes else ""))
        if cr.impact:
            L.append("- **Affected:** " + "; ".join(f"{k}: {', '.join(v)}" for k, v in cr.impact.items()))
        L.append("")
    return "\n".join(L).rstrip() + "\n"
